POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXRub3ZpdXNlckBnbWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNjc3NTg4Nzc0fQ.SyhaJgZxaO_ol4B7pHqaLwIbjREnt_ExS_8Bt7a372o

{
    "author": "Novi User",
    "url": "https://google.com/",
    "title": "Opet Novi blog",
    "year": 1992
}